[DEFAULT]
# Please set the real path to Rscript.exe on your computer (note: do not use quotes)
# Windows example: C:\Program Files\R\R-4.2.2\bin\Rscript.exe
R_EXEC_PATH = YOUR_RSCRIPT_PATH

# Please fill in your Materials Project API Key
# Apply at: https://next-gen.materialsproject.org/api
MP_API_KEY = YOUR_MP_API_KEY

# Deepseek API Key
DS_API_KEY = YOUR_DS_API_KEY

# Deepseek Model: deepseek-chat (flash, saves tokens) / deepseek-v4-pro
DS_MODEL = deepseek-chat

# HuggingFace Token
HF_TOKEN = YOUR_HF_TOKEN